/**
 * ts_cs.js
 * GUI 設計服務頁面的多語系設定（繁中 / 簡中 / 英文）
 *
 * 說明：
 * - 所有可翻譯文字或圖片路徑，都透過 data-i18n 與 data-i18n-attr 控制。
 * - 目前 zh-TW 為原始文字，其餘語系預設先複製 zh-TW 內容，方便後續逐步翻譯。
 * - 若某語系缺少對應 key，會自動 fallback 到 zh-TW，確保畫面不會出現空白。
 *
 * 使用方式：
 * - 調整/新增文字：請在 GUI_TRANSLATIONS 對應語系中修改 key 對應的字串。
 * - 調整圖片：找到例如 'img.process_overview.src' 的項目，
 *             將不同語系的路徑改成對應檔案，例如：
 *             zh-TW: images/process_overview_tw.png
 *             en   : images/process_overview_en.png
 *             zh-CN: images/process_overview_cn.png
 */

(function() {
  const GUI_TRANSLATIONS = {
    'zh-TW': {
      'img.pricing_table.src': 'images/pricing_table.png',
      'img.process_overview.src': 'images/process_overview.png',
      'img.process_stage_1.src': 'images/process_stage_1.png',
      'img.process_stage_2.src': 'images/process_stage_2.png',
      'img.process_stage_3.src': 'images/process_stage_3.png',
      'nav.brand': '橘皮客 GUI 設計服務',
      'nav.home': '回首頁',
      'page.brand': '橘皮客自動化　Gary Chu',
      'page.footer': '本頁內容僅供專案合作與需求溝通使用。若有未盡事宜，歡迎直接與開發方聯繫討論。',
      'page.subtitle': '在自動化與資料導向的時代，我們協助您打造穩定、可靠、具彈性的專業 GUI 介面。',
      'page.title': 'GUI 設計服務流程條款',
      'section.about.list1': '韌性（Resilience）：面對專案中不可避免的挑戰與突發狀況，我們具備足夠的耐力與解決問題的能力，確保系統最終能穩定落地。',
      'section.about.list2': '毅力（Perseverance）：我們不斷優化模組化架構與開發流程，憑藉日積月累的經驗與持續投入，為客戶帶來可靠且高品質的成果。',
      'section.about.list3': '彈性（Flexibility）：每個客戶的需求都不同，我們擅長在既有框架上快速調整，提供最適合的方案，無論是 GUI 設計、硬體控制還是系統整合。',
      'section.about.list4': '我們能夠提供的服務範圍',
      'section.about.list5': '專案的開發流程與時間規劃',
      'section.about.list6': '雙方應遵守的合作條款',
      'section.about.list7': '各項服務的價值與成本依據',
      'section.about.p1': '在當今自動化與數據導向的時代，人機介面（GUI）已不僅僅是顯示數據的工具，             而是客戶與系統互動的核心。',
      'section.about.p2': '我們深信，一個好的設計服務不只是完成專案，而是要陪伴客戶一起走過挑戰，             確保每一步都能帶來價值。',
      'section.about.p3': '因此，我們的服務理念建立在三個核心精神上：',
      'section.about.p4': '本文件的目的，是希望客戶在專案開始之前，就能清楚了解：',
      'section.about.p5': '透過這樣的規劃，我們不僅交付一個 GUI，而是交付一個能伴隨企業成長、             具備韌性、毅力與彈性的完整解決方案，讓客戶能安心專注於核心業務。',
      'section.about.title': '關於橘皮客',
      'section.client_checklist.item1': '現有系統或 Demo 影片（若有）：可以是手機拍攝的操作影片，方便我們了解實際流程。',
      'section.client_checklist.item2': '儀器與硬體清單：包含儀器型號、通訊介面（UART / I2C / SPI / GPIB / LAN / USB）等。',
      'section.client_checklist.item3': '通訊協議與指令文件：例如 SCPI 指令表、通訊時序圖、廠商提供的 PDF 等。',
      'section.client_checklist.item4': '測試流程或 SOP 文件：說明平時如何操作、量測哪些數據、判斷 Pass / Fail 的條件。',
      'section.client_checklist.item5': '報表範例或欄位需求：可提供舊報表或 Excel 範本，標註必需欄位與格式要求。',
      'section.client_checklist.item6': 'GUI 草圖或舊 GUI 截圖（若有）：有助於我們理解排版習慣與風格偏好。',
      'section.client_checklist.item7': '預計使用環境與電腦規格：例如 OS 版本、螢幕解析度、是否在產線環境等。',
      'section.client_checklist.item8': '專案時程與內部里程碑：若您已有內部專案排程，可一併提供，方便我們對齊時程。',
      'section.client_checklist.note': '若以上資料尚未齊備，也歡迎先與我們討論，我們可以協助一起整理，逐步補齊。專案的規格剛開始很難完全確定，但希望透過這份文件以及後續的郵件、開會討論可以協助您逐步達成您喜要的目標!',
      'section.client_checklist.p1': '為了縮短前期溝通時間並提升專案準確度，建議您在首次會議或需求提出前，             儘可能準備以下資料（可先準備已有的部分，其餘可於後續補充）：',
      'section.client_checklist.title': '客戶需事先準備的資料',
      'section.contact.client_eng_item1': '技術討論工程師（負責專案進行中的技術細節討論）稱呼：__________________Mail：__________________手機或 Line ID：__________________',
      'section.contact.client_eng_mail': 'Mail：__________________',
      'section.contact.client_eng_name': '稱呼：__________________',
      'section.contact.client_eng_phone': '手機或 Line ID：__________________',
      'section.contact.client_pm_item1': '專案經理（負責時程、功能與一般溝通）稱呼：__________________Mail：__________________手機或 Line ID：__________________',
      'section.contact.client_pm_mail': 'Mail：__________________',
      'section.contact.client_pm_name': '稱呼：__________________',
      'section.contact.client_pm_phone': '手機或 Line ID：__________________',
      'section.contact.client_pm_title': '客戶端聯絡窗口',
      'section.contact.dev_engineer': '技術工程師：Gary Chu',
      'section.contact.dev_line': 'Line ID：tigarychu',
      'section.contact.dev_mail': 'Mail：gary49902210@gmail.com',
      'section.contact.dev_title': '開發方聯絡窗口（橘皮客自動化）',
      'section.contact.p1': '為了讓專案能順利進行，請客戶提供以下兩位聯絡人資訊：',
      'section.contact.title': '聯絡資料',
      'section.gui_style.item1': '技術型 / 工具型：偏向工程師使用，畫面以表格、參數與 Log 為主，重視資訊密度與操作效率。',
      'section.gui_style.item2': '儀表板型：使用大型數值、指針表、狀態燈號等呈現重點資訊，適合監控與展示。',
      'section.gui_style.item3': '簡潔扁平風格：按鈕與元件設計較為現代、線條簡單，適合對外展示或客戶端使用。',
      'section.gui_style.item4': '客製混合風格：若您有既有軟體或品牌識別（Logo、色系），我們可以依現有風格調整 GUI 視覺。',
      'section.gui_style.note': '若目前尚無特別偏好，也可以先以「清楚、好操作」為主，我們會依常見工程用 GUI 的習慣進行設計。',
      'section.gui_style.p1': '雖然本服務主要以技術功能與穩定性為優先，但介面風格仍會影響使用體驗。             您可以先思考希望整體感覺偏向哪一類型，我們會在設計時盡量配合：',
      'section.gui_style.title': 'GUI 設計風格示例',
      'section.pricing.img_caption': '圖示：GUI 設計服務價目表（請依實際圖片路徑替換 src）',
      'section.pricing.note': '※ 若有大型專案、長期合作或需多階段擴充之情況，歡迎洽談專案制報價。',
      'section.pricing.p1': '各功能項目請參考下方價目表示意圖。實際費用可能會依照             專案複雜度、客製程度及整體規劃而有所調整。',
      'section.pricing.p2': '每一個專案方案，預設皆包含專案完成後 3 個月內，每月 3 小時的客戶服務（線上討論／技術諮詢）。',
      'section.pricing.title': '價目表',
      'section.process.detail_flow_p1': '更細部的階段性流程，將依下列示意圖說明。若您已有內部標準開發流程，             也可以在雙方討論後進行整合。',
      'section.process.detail_flow_title': '階段性細節流程',
      'section.process.img_main_caption': '圖示：專案主要開發流程（請依實際圖片路徑替換 src）',
      'section.process.img_stage1_caption': '圖示：專案階段性流程（第一部分）',
      'section.process.img_stage2_caption': '圖示：專案階段性流程（第二部分）',
      'section.process.img_stage3_caption': '圖示：專案階段性流程（第三部分）',
      'section.process.p1': '企劃進行時，開發方與客戶需要共同配合，並留意以下主要流程。',
      'section.process.rough_timeline_note': '實際時程會依專案範圍、技術難度及資源配合情況調整，將於專案計畫書中明確載明。',
      'section.process.title': '專案開發流程',
      'section.req_guide.end_note': '以上內容不需要一次完成，只要先提供大致方向即可。             我們會在需求訪談與會議中協助補充細節，並整理為正式的專案計畫書。',
      'section.req_guide.flow_item1': '開啟程式 → 選擇 COM Port → 按下「連線」',
      'section.req_guide.flow_item2': '載入測試條件檔 → 按下「開始測試」',
      'section.req_guide.flow_item3': '等測試完成 → 顯示結果 → 匯出報表到指定資料夾',
      'section.req_guide.flow_note': '若有多種情境（例如：工程模式 / 操作員模式），也可以分別描述，我們會協助拆分為不同頁面或權限。',
      'section.req_guide.flow_p1': '請以「使用者實際操作」的角度，簡單描述一個完整流程。例如：',
      'section.req_guide.flow_title': '2. 操作流程（使用步驟）',
      'section.req_guide.gui_layout_item1': '主視窗大致尺寸（例如：1280×720 或全螢幕）',
      'section.req_guide.gui_layout_item2': '按鈕、輸入欄位、列表、圖表等大致位置',
      'section.req_guide.gui_layout_item3': '是否需要多分頁（Tab）或多個對話框視窗',
      'section.req_guide.gui_layout_p1': '您可以使用簡單手繪、PowerPoint、Excel 或任何工具，畫出想像中的畫面配置，             並標註大致位置與功能，例如：「左側為測試設定區、右側為即時曲線圖、下方為 Log 區」。',
      'section.req_guide.gui_layout_title': '1. GUI 版面與畫面配置',
      'section.req_guide.hw_item1': '儀器或搭配硬體型號與廠牌（例如：電源供應器、DMM、示波器、Pico 等）',
      'section.req_guide.hw_item2': '通訊介面：UART / I2C / SPI / GPIB / LAN / USB 等',
      'section.req_guide.hw_item3': '是否有現成範例程式（例如：Python、LabVIEW、C）',
      'section.req_guide.hw_item4': '是否能提供通訊協議、指令表或 SCPI 命令文件',
      'section.req_guide.hw_p1': '若 GUI 需要控制儀器、測試板或其他硬體，請盡量提供以下資訊：',
      'section.req_guide.hw_title': '3. 儀器／硬體控制需求',
      'section.req_guide.intro': '為了讓我們能更精準估算工時與成本，並減少後續反覆修改，             建議您在提出需求時，盡量依照下列項目進行描述。             不需要一次寫得非常完整，可以先用簡單條列，我們會在郵件或會議中協助補充與釐清。',
      'section.req_guide.report_item1': '是否需要 Excel 報表（請提供範例檔或欄位名稱）',
      'section.req_guide.report_item2': '是否需要 CSV / JSON 等機器可讀格式',
      'section.req_guide.report_item3': '是否需支援多次量測結果比對或合併報告',
      'section.req_guide.report_p1': '請簡單說明您希望最後的測試結果以什麼形式呈現，例如：',
      'section.req_guide.report_title': '4. 報表與資料輸出需求',
      'section.req_guide.title': '客戶需求填寫指引',
      'section.req_guide.user_item1': '主要使用者類型：研發 / 量產 / 實驗室 / 教學 等',
      'section.req_guide.user_item2': '是否需要權限區分（例如：一般使用者 vs 管理者）',
      'section.req_guide.user_item3': '預期每天或每週使用頻率',
      'section.req_guide.user_p1': '不同使用者（研發工程師、產線作業員、FAE、客戶端工程師）對介面與功能的需求會不同。             若您能提供預期使用族群與環境，我們可以在設計上更貼近實際需求。',
      'section.req_guide.user_title': '5. 使用者族群與使用情境',
      'section.scope.func1': 'GUI 主視窗設計、選單列（menubar）、對話框',
      'section.scope.func2': '資料顯示（表格、圖表、即時數據）',
      'section.scope.func3': '儀器／硬體控制介面（UART、I2C、SPI、GPIB）',
      'section.scope.func4': '報告輸出（Excel、CSV、自動化格式）',
      'section.scope.func_title': '功能性範圍',
      'section.scope.nonfunc1': '不包含硬體現場調試（如需，將另行報價）',
      'section.scope.nonfunc2': '不包含第三方商業授權軟體費用（例如專業版工具授權等）',
      'section.scope.nonfunc_title': '非功能性範圍（排除事項）',
      'section.scope.title': '服務範圍',
      'section.terms.accept_p1': '當專案完成時，開發方將與客戶於會議中進行測試與驗收。             若專案涉及實體硬體，則需安排實體會議或現場測試。',
      'section.terms.accept_p2': '驗收將依照訂金前雙方確認之專案計畫書與驗收項目進行。             開發方應針對功能缺失進行修正，但不包含 GUI 額外美化調整。             若此階段客戶提出新的需求，將視為新專案或新階段內容，需另行評估與報價。',
      'section.terms.accept_p3': '專案成果交付後，客戶應於一週內支付尾款，以完成結案程序。             結案後，若遇到非原專案計畫中功能缺失之修改需求，將視為新專案需求。',
      'section.terms.accept_title': '六、測試驗收與成果交付',
      'section.terms.change_list1': '小幅調整（通常不另外計價）：文案修正、欄位名稱調整、顏色或字體微調等，不影響整體架構者。',
      'section.terms.change_list2': '中度變更（需評估追加費用）：新增按鈕與對應功能、新增報表格式、增加與新儀器的對接等。',
      'section.terms.change_list3': '重大變更（需重新估價或開新專案）：主要流程改寫、測試邏輯全面調整、作業系統平台改變等。',
      'section.terms.change_note': '通常在初版 GUI 確認後，若版面或流程有大幅變更需求，我們會先與您說明影響範圍與工時，             經雙方同意後再進行調整。',
      'section.terms.change_p1': '為避免專案過程中因需求持續變動而導致時程與成本大幅增加，             雙方將以「專案計畫書」作為主要依據，必要時再透過「變更單」進行調整。',
      'section.terms.change_title': '三、變更需求與加價原則',
      'section.terms.need_eval_list1': '提供 Demo 機與示範操作，並向開發方說明實際需求。',
      'section.terms.need_eval_list2': '由開發方進行 Log 抓取，評估介面協定與實作可行性。',
      'section.terms.need_eval_list3': '開發方與客戶技術工程師進行技術討論，確認需求細節與可行性。',
      'section.terms.need_eval_p1': '開發方將依照客戶提供的相關資料，分析技術可行性、估算開發工時與成本，             並提出所需之測試儀器與相關資源，請客戶評估是否能提供開發所需條件。             若無法提供，雙方將另行討論替代方案與調整方式。',
      'section.terms.need_eval_p2': '對於已有範例程式或明確客製目標的專案，客戶需在韌體或驅動開發前，             提供完整可測試之硬體與接線資訊，以確保能開發出功能相同或可正常對接之系統。             主要需配合事項如下：',
      'section.terms.need_eval_p3': '根據專案複雜程度，如有必要，可行性評估階段可能需收取評估費，將於事前與客戶說明。',
      'section.terms.need_eval_title': '一、需求討論與可行性評估',
      'section.terms.plan_update_p1': '開發方應於收取訂金前提供專案計畫書，             內容包括：對專案需求功能的理解、預計驗收項目與驗收方式。             此文件將作為專案完成時之驗收依據，雙方皆不得單方面修改專案目標與驗收項目。',
      'section.terms.plan_update_p2': '專案啟動後，每2～3 週開發方將向客戶進行進度彙報與已完成功能之展示，             以線上會議為主，並將相關資料上傳至雲端硬碟供客戶參考。             客戶須於會議中協助確認功能是否符合需求，以避免方向偏差造成交期延誤。',
      'section.terms.plan_update_p3': 'GUI（使用者介面）設計將於開發過程中提供初稿給客戶審閱與確認。             完成確認後，除專案計畫書原列之功能必要調整外，將不再進行額外美化或大幅版面修改。',
      'section.terms.plan_update_p4': '客戶應盡量於前期明確提供 GUI 版面初始設計與後續調整需求，             以降低來回修正次數。專案提供3 次免費版面修改，             超過 3 次者，將以每次新台幣 2,000 元計入尾款。             若為開發方遺漏之需求，則不計入此修改次數。',
      'section.terms.plan_update_p5': '開發方與客戶皆需指定一位專案經理與技術溝通窗口（可為同一人），             遇到非預期專案調整或技術討論需求時，得以迅速聯繫並維持專案順利進行。',
      'section.terms.plan_update_title': '五、開發規劃與進度更新',
      'section.terms.quote_deposit_p1': '確認需求並完成可行性評估後，開發方將依結果進行專案時程規劃與報價。             雙方確認專案目標、報價與時程無誤並達成共識後，             客戶需支付20% 訂金，以確認專案計畫書內所載之目標與範圍。',
      'section.terms.quote_deposit_p2': '專案啟動後開始計算時程。若後續有新增或重大修改需求，             需針對新增項目另行估價。若遇開發方無法完成之情況，             將與客戶討論調整計畫與報價方式。',
      'section.terms.quote_deposit_p3': '若客戶需開發方提供原始碼，將依專案大小與難度另行評估費用，             並提供具詳細註解之程式碼。',
      'section.terms.quote_deposit_p4': '訂金收據將以開發方銀行帳戶記錄截圖方式回傳給客戶留存。',
      'section.terms.quote_deposit_title': '二、報價與訂金',
      'section.terms.terminate_list1': '若因開發方遇不可預期因素（例如評估錯誤等）需中止專案，                 客戶可選擇要求全額退還訂金，或接收已完成之部分成果並由雙方協議處理方式。',
      'section.terms.terminate_list2': '若因客戶遇不可預期因素需中止專案，開發方得依照已執行之工作項目與進度進行收費。',
      'section.terms.terminate_title': '四、中止條款與責任歸屬',
      'section.terms.title': '合作條款細節',
      'section.terms.warranty_p1': '專案成果交付後，開發方將提供2 個月功能保固，             期間若發現專案功能缺失，可免費協助修正。',
      'section.terms.warranty_p2': '此外，專案結案後6 個月內，             每月提供最多3 小時的線上討論與售後技術諮詢服務。             若超過此時數，或需開發方到場（on-site）支援，將另行評估費用。',
      'section.terms.warranty_title': '七、後續維護、服務與保固',
      'section.use_cases.item1': '電腦作業系統：Windows 11 24H2',
      'section.use_cases.item2': '報告輸入／輸出工具：Excel 2019 64-bit',
      'section.use_cases.item3': '必要系統驅動程式：NI MAX（NI VISA 488.2）USB-RS-232 相關驅動',
      'section.use_cases.note': '※ 若系統需支援其他版本作業系統或額外軟體環境，請於需求討論階段主動說明。※ 必要系統驅動程式部分若有搭配其他的韌體或硬體，可能增加額外使用限制',
      'section.use_cases.p1': '本服務主要針對符合下列開發規格的軟硬體系統，             其餘操作環境若有需求，歡迎另行討論可行性。',
      'section.use_cases.subitem1': 'NI MAX（NI VISA 488.2）',
      'section.use_cases.subitem2': 'USB-RS-232 相關驅動',
      'section.use_cases.title': '應用場景',
      'toc.about': '關於橘皮客',
      'toc.client_checklist': '客戶需事先準備的資料',
      'toc.contact': '聯絡資料',
      'toc.gui_style': 'GUI 設計風格示例',
      'toc.pricing': '價目表',
      'toc.process': '專案開發流程',
      'toc.requirements_guide': '客戶需求填寫指引',
      'toc.scope': '服務範圍',
      'toc.terms': '合作條款細節',
      'toc.title': '目錄',
      'toc.use_cases': '應用場景',
    },
    'en': {
      // TODO: 請依需求逐步翻譯為英文，以下為預設先沿用繁中內容，避免畫面空白。
      'img.pricing_table.src': 'images/pricing_table.png',
      'img.process_overview.src': 'images/process_overview.png',
      'img.process_stage_1.src': 'images/process_stage_1.png',
      'img.process_stage_2.src': 'images/process_stage_2.png',
      'img.process_stage_3.src': 'images/process_stage_3.png',
      'nav.brand': '橘皮客 GUI 設計服務',
      'nav.home': '回首頁',
      'page.brand': '橘皮客自動化　Gary Chu',
      'page.footer': '本頁內容僅供專案合作與需求溝通使用。若有未盡事宜，歡迎直接與開發方聯繫討論。',
      'page.subtitle': '在自動化與資料導向的時代，我們協助您打造穩定、可靠、具彈性的專業 GUI 介面。',
      'page.title': 'GUI 設計服務流程條款',
      'section.about.list1': '韌性（Resilience）：面對專案中不可避免的挑戰與突發狀況，我們具備足夠的耐力與解決問題的能力，確保系統最終能穩定落地。',
      'section.about.list2': '毅力（Perseverance）：我們不斷優化模組化架構與開發流程，憑藉日積月累的經驗與持續投入，為客戶帶來可靠且高品質的成果。',
      'section.about.list3': '彈性（Flexibility）：每個客戶的需求都不同，我們擅長在既有框架上快速調整，提供最適合的方案，無論是 GUI 設計、硬體控制還是系統整合。',
      'section.about.list4': '我們能夠提供的服務範圍',
      'section.about.list5': '專案的開發流程與時間規劃',
      'section.about.list6': '雙方應遵守的合作條款',
      'section.about.list7': '各項服務的價值與成本依據',
      'section.about.p1': '在當今自動化與數據導向的時代，人機介面（GUI）已不僅僅是顯示數據的工具，             而是客戶與系統互動的核心。',
      'section.about.p2': '我們深信，一個好的設計服務不只是完成專案，而是要陪伴客戶一起走過挑戰，             確保每一步都能帶來價值。',
      'section.about.p3': '因此，我們的服務理念建立在三個核心精神上：',
      'section.about.p4': '本文件的目的，是希望客戶在專案開始之前，就能清楚了解：',
      'section.about.p5': '透過這樣的規劃，我們不僅交付一個 GUI，而是交付一個能伴隨企業成長、             具備韌性、毅力與彈性的完整解決方案，讓客戶能安心專注於核心業務。',
      'section.about.title': '關於橘皮客',
      'section.client_checklist.item1': '現有系統或 Demo 影片（若有）：可以是手機拍攝的操作影片，方便我們了解實際流程。',
      'section.client_checklist.item2': '儀器與硬體清單：包含儀器型號、通訊介面（UART / I2C / SPI / GPIB / LAN / USB）等。',
      'section.client_checklist.item3': '通訊協議與指令文件：例如 SCPI 指令表、通訊時序圖、廠商提供的 PDF 等。',
      'section.client_checklist.item4': '測試流程或 SOP 文件：說明平時如何操作、量測哪些數據、判斷 Pass / Fail 的條件。',
      'section.client_checklist.item5': '報表範例或欄位需求：可提供舊報表或 Excel 範本，標註必需欄位與格式要求。',
      'section.client_checklist.item6': 'GUI 草圖或舊 GUI 截圖（若有）：有助於我們理解排版習慣與風格偏好。',
      'section.client_checklist.item7': '預計使用環境與電腦規格：例如 OS 版本、螢幕解析度、是否在產線環境等。',
      'section.client_checklist.item8': '專案時程與內部里程碑：若您已有內部專案排程，可一併提供，方便我們對齊時程。',
      'section.client_checklist.note': '若以上資料尚未齊備，也歡迎先與我們討論，我們可以協助一起整理，逐步補齊。專案的規格剛開始很難完全確定，但希望透過這份文件以及後續的郵件、開會討論可以協助您逐步達成您喜要的目標!',
      'section.client_checklist.p1': '為了縮短前期溝通時間並提升專案準確度，建議您在首次會議或需求提出前，             儘可能準備以下資料（可先準備已有的部分，其餘可於後續補充）：',
      'section.client_checklist.title': '客戶需事先準備的資料',
      'section.contact.client_eng_item1': '技術討論工程師（負責專案進行中的技術細節討論）稱呼：__________________Mail：__________________手機或 Line ID：__________________',
      'section.contact.client_eng_mail': 'Mail：__________________',
      'section.contact.client_eng_name': '稱呼：__________________',
      'section.contact.client_eng_phone': '手機或 Line ID：__________________',
      'section.contact.client_pm_item1': '專案經理（負責時程、功能與一般溝通）稱呼：__________________Mail：__________________手機或 Line ID：__________________',
      'section.contact.client_pm_mail': 'Mail：__________________',
      'section.contact.client_pm_name': '稱呼：__________________',
      'section.contact.client_pm_phone': '手機或 Line ID：__________________',
      'section.contact.client_pm_title': '客戶端聯絡窗口',
      'section.contact.dev_engineer': '技術工程師：Gary Chu',
      'section.contact.dev_line': 'Line ID：tigarychu',
      'section.contact.dev_mail': 'Mail：gary49902210@gmail.com',
      'section.contact.dev_title': '開發方聯絡窗口（橘皮客自動化）',
      'section.contact.p1': '為了讓專案能順利進行，請客戶提供以下兩位聯絡人資訊：',
      'section.contact.title': '聯絡資料',
      'section.gui_style.item1': '技術型 / 工具型：偏向工程師使用，畫面以表格、參數與 Log 為主，重視資訊密度與操作效率。',
      'section.gui_style.item2': '儀表板型：使用大型數值、指針表、狀態燈號等呈現重點資訊，適合監控與展示。',
      'section.gui_style.item3': '簡潔扁平風格：按鈕與元件設計較為現代、線條簡單，適合對外展示或客戶端使用。',
      'section.gui_style.item4': '客製混合風格：若您有既有軟體或品牌識別（Logo、色系），我們可以依現有風格調整 GUI 視覺。',
      'section.gui_style.note': '若目前尚無特別偏好，也可以先以「清楚、好操作」為主，我們會依常見工程用 GUI 的習慣進行設計。',
      'section.gui_style.p1': '雖然本服務主要以技術功能與穩定性為優先，但介面風格仍會影響使用體驗。             您可以先思考希望整體感覺偏向哪一類型，我們會在設計時盡量配合：',
      'section.gui_style.title': 'GUI 設計風格示例',
      'section.pricing.img_caption': '圖示：GUI 設計服務價目表（請依實際圖片路徑替換 src）',
      'section.pricing.note': '※ 若有大型專案、長期合作或需多階段擴充之情況，歡迎洽談專案制報價。',
      'section.pricing.p1': '各功能項目請參考下方價目表示意圖。實際費用可能會依照             專案複雜度、客製程度及整體規劃而有所調整。',
      'section.pricing.p2': '每一個專案方案，預設皆包含專案完成後 3 個月內，每月 3 小時的客戶服務（線上討論／技術諮詢）。',
      'section.pricing.title': '價目表',
      'section.process.detail_flow_p1': '更細部的階段性流程，將依下列示意圖說明。若您已有內部標準開發流程，             也可以在雙方討論後進行整合。',
      'section.process.detail_flow_title': '階段性細節流程',
      'section.process.img_main_caption': '圖示：專案主要開發流程（請依實際圖片路徑替換 src）',
      'section.process.img_stage1_caption': '圖示：專案階段性流程（第一部分）',
      'section.process.img_stage2_caption': '圖示：專案階段性流程（第二部分）',
      'section.process.img_stage3_caption': '圖示：專案階段性流程（第三部分）',
      'section.process.p1': '企劃進行時，開發方與客戶需要共同配合，並留意以下主要流程。',
      'section.process.rough_timeline_note': '實際時程會依專案範圍、技術難度及資源配合情況調整，將於專案計畫書中明確載明。',
      'section.process.title': '專案開發流程',
      'section.req_guide.end_note': '以上內容不需要一次完成，只要先提供大致方向即可。             我們會在需求訪談與會議中協助補充細節，並整理為正式的專案計畫書。',
      'section.req_guide.flow_item1': '開啟程式 → 選擇 COM Port → 按下「連線」',
      'section.req_guide.flow_item2': '載入測試條件檔 → 按下「開始測試」',
      'section.req_guide.flow_item3': '等測試完成 → 顯示結果 → 匯出報表到指定資料夾',
      'section.req_guide.flow_note': '若有多種情境（例如：工程模式 / 操作員模式），也可以分別描述，我們會協助拆分為不同頁面或權限。',
      'section.req_guide.flow_p1': '請以「使用者實際操作」的角度，簡單描述一個完整流程。例如：',
      'section.req_guide.flow_title': '2. 操作流程（使用步驟）',
      'section.req_guide.gui_layout_item1': '主視窗大致尺寸（例如：1280×720 或全螢幕）',
      'section.req_guide.gui_layout_item2': '按鈕、輸入欄位、列表、圖表等大致位置',
      'section.req_guide.gui_layout_item3': '是否需要多分頁（Tab）或多個對話框視窗',
      'section.req_guide.gui_layout_p1': '您可以使用簡單手繪、PowerPoint、Excel 或任何工具，畫出想像中的畫面配置，             並標註大致位置與功能，例如：「左側為測試設定區、右側為即時曲線圖、下方為 Log 區」。',
      'section.req_guide.gui_layout_title': '1. GUI 版面與畫面配置',
      'section.req_guide.hw_item1': '儀器或搭配硬體型號與廠牌（例如：電源供應器、DMM、示波器、Pico 等）',
      'section.req_guide.hw_item2': '通訊介面：UART / I2C / SPI / GPIB / LAN / USB 等',
      'section.req_guide.hw_item3': '是否有現成範例程式（例如：Python、LabVIEW、C）',
      'section.req_guide.hw_item4': '是否能提供通訊協議、指令表或 SCPI 命令文件',
      'section.req_guide.hw_p1': '若 GUI 需要控制儀器、測試板或其他硬體，請盡量提供以下資訊：',
      'section.req_guide.hw_title': '3. 儀器／硬體控制需求',
      'section.req_guide.intro': '為了讓我們能更精準估算工時與成本，並減少後續反覆修改，             建議您在提出需求時，盡量依照下列項目進行描述。             不需要一次寫得非常完整，可以先用簡單條列，我們會在郵件或會議中協助補充與釐清。',
      'section.req_guide.report_item1': '是否需要 Excel 報表（請提供範例檔或欄位名稱）',
      'section.req_guide.report_item2': '是否需要 CSV / JSON 等機器可讀格式',
      'section.req_guide.report_item3': '是否需支援多次量測結果比對或合併報告',
      'section.req_guide.report_p1': '請簡單說明您希望最後的測試結果以什麼形式呈現，例如：',
      'section.req_guide.report_title': '4. 報表與資料輸出需求',
      'section.req_guide.title': '客戶需求填寫指引',
      'section.req_guide.user_item1': '主要使用者類型：研發 / 量產 / 實驗室 / 教學 等',
      'section.req_guide.user_item2': '是否需要權限區分（例如：一般使用者 vs 管理者）',
      'section.req_guide.user_item3': '預期每天或每週使用頻率',
      'section.req_guide.user_p1': '不同使用者（研發工程師、產線作業員、FAE、客戶端工程師）對介面與功能的需求會不同。             若您能提供預期使用族群與環境，我們可以在設計上更貼近實際需求。',
      'section.req_guide.user_title': '5. 使用者族群與使用情境',
      'section.scope.func1': 'GUI 主視窗設計、選單列（menubar）、對話框',
      'section.scope.func2': '資料顯示（表格、圖表、即時數據）',
      'section.scope.func3': '儀器／硬體控制介面（UART、I2C、SPI、GPIB）',
      'section.scope.func4': '報告輸出（Excel、CSV、自動化格式）',
      'section.scope.func_title': '功能性範圍',
      'section.scope.nonfunc1': '不包含硬體現場調試（如需，將另行報價）',
      'section.scope.nonfunc2': '不包含第三方商業授權軟體費用（例如專業版工具授權等）',
      'section.scope.nonfunc_title': '非功能性範圍（排除事項）',
      'section.scope.title': '服務範圍',
      'section.terms.accept_p1': '當專案完成時，開發方將與客戶於會議中進行測試與驗收。             若專案涉及實體硬體，則需安排實體會議或現場測試。',
      'section.terms.accept_p2': '驗收將依照訂金前雙方確認之專案計畫書與驗收項目進行。             開發方應針對功能缺失進行修正，但不包含 GUI 額外美化調整。             若此階段客戶提出新的需求，將視為新專案或新階段內容，需另行評估與報價。',
      'section.terms.accept_p3': '專案成果交付後，客戶應於一週內支付尾款，以完成結案程序。             結案後，若遇到非原專案計畫中功能缺失之修改需求，將視為新專案需求。',
      'section.terms.accept_title': '六、測試驗收與成果交付',
      'section.terms.change_list1': '小幅調整（通常不另外計價）：文案修正、欄位名稱調整、顏色或字體微調等，不影響整體架構者。',
      'section.terms.change_list2': '中度變更（需評估追加費用）：新增按鈕與對應功能、新增報表格式、增加與新儀器的對接等。',
      'section.terms.change_list3': '重大變更（需重新估價或開新專案）：主要流程改寫、測試邏輯全面調整、作業系統平台改變等。',
      'section.terms.change_note': '通常在初版 GUI 確認後，若版面或流程有大幅變更需求，我們會先與您說明影響範圍與工時，             經雙方同意後再進行調整。',
      'section.terms.change_p1': '為避免專案過程中因需求持續變動而導致時程與成本大幅增加，             雙方將以「專案計畫書」作為主要依據，必要時再透過「變更單」進行調整。',
      'section.terms.change_title': '三、變更需求與加價原則',
      'section.terms.need_eval_list1': '提供 Demo 機與示範操作，並向開發方說明實際需求。',
      'section.terms.need_eval_list2': '由開發方進行 Log 抓取，評估介面協定與實作可行性。',
      'section.terms.need_eval_list3': '開發方與客戶技術工程師進行技術討論，確認需求細節與可行性。',
      'section.terms.need_eval_p1': '開發方將依照客戶提供的相關資料，分析技術可行性、估算開發工時與成本，             並提出所需之測試儀器與相關資源，請客戶評估是否能提供開發所需條件。             若無法提供，雙方將另行討論替代方案與調整方式。',
      'section.terms.need_eval_p2': '對於已有範例程式或明確客製目標的專案，客戶需在韌體或驅動開發前，             提供完整可測試之硬體與接線資訊，以確保能開發出功能相同或可正常對接之系統。             主要需配合事項如下：',
      'section.terms.need_eval_p3': '根據專案複雜程度，如有必要，可行性評估階段可能需收取評估費，將於事前與客戶說明。',
      'section.terms.need_eval_title': '一、需求討論與可行性評估',
      'section.terms.plan_update_p1': '開發方應於收取訂金前提供專案計畫書，             內容包括：對專案需求功能的理解、預計驗收項目與驗收方式。             此文件將作為專案完成時之驗收依據，雙方皆不得單方面修改專案目標與驗收項目。',
      'section.terms.plan_update_p2': '專案啟動後，每2～3 週開發方將向客戶進行進度彙報與已完成功能之展示，             以線上會議為主，並將相關資料上傳至雲端硬碟供客戶參考。             客戶須於會議中協助確認功能是否符合需求，以避免方向偏差造成交期延誤。',
      'section.terms.plan_update_p3': 'GUI（使用者介面）設計將於開發過程中提供初稿給客戶審閱與確認。             完成確認後，除專案計畫書原列之功能必要調整外，將不再進行額外美化或大幅版面修改。',
      'section.terms.plan_update_p4': '客戶應盡量於前期明確提供 GUI 版面初始設計與後續調整需求，             以降低來回修正次數。專案提供3 次免費版面修改，             超過 3 次者，將以每次新台幣 2,000 元計入尾款。             若為開發方遺漏之需求，則不計入此修改次數。',
      'section.terms.plan_update_p5': '開發方與客戶皆需指定一位專案經理與技術溝通窗口（可為同一人），             遇到非預期專案調整或技術討論需求時，得以迅速聯繫並維持專案順利進行。',
      'section.terms.plan_update_title': '五、開發規劃與進度更新',
      'section.terms.quote_deposit_p1': '確認需求並完成可行性評估後，開發方將依結果進行專案時程規劃與報價。             雙方確認專案目標、報價與時程無誤並達成共識後，             客戶需支付20% 訂金，以確認專案計畫書內所載之目標與範圍。',
      'section.terms.quote_deposit_p2': '專案啟動後開始計算時程。若後續有新增或重大修改需求，             需針對新增項目另行估價。若遇開發方無法完成之情況，             將與客戶討論調整計畫與報價方式。',
      'section.terms.quote_deposit_p3': '若客戶需開發方提供原始碼，將依專案大小與難度另行評估費用，             並提供具詳細註解之程式碼。',
      'section.terms.quote_deposit_p4': '訂金收據將以開發方銀行帳戶記錄截圖方式回傳給客戶留存。',
      'section.terms.quote_deposit_title': '二、報價與訂金',
      'section.terms.terminate_list1': '若因開發方遇不可預期因素（例如評估錯誤等）需中止專案，                 客戶可選擇要求全額退還訂金，或接收已完成之部分成果並由雙方協議處理方式。',
      'section.terms.terminate_list2': '若因客戶遇不可預期因素需中止專案，開發方得依照已執行之工作項目與進度進行收費。',
      'section.terms.terminate_title': '四、中止條款與責任歸屬',
      'section.terms.title': '合作條款細節',
      'section.terms.warranty_p1': '專案成果交付後，開發方將提供2 個月功能保固，             期間若發現專案功能缺失，可免費協助修正。',
      'section.terms.warranty_p2': '此外，專案結案後6 個月內，             每月提供最多3 小時的線上討論與售後技術諮詢服務。             若超過此時數，或需開發方到場（on-site）支援，將另行評估費用。',
      'section.terms.warranty_title': '七、後續維護、服務與保固',
      'section.use_cases.item1': '電腦作業系統：Windows 11 24H2',
      'section.use_cases.item2': '報告輸入／輸出工具：Excel 2019 64-bit',
      'section.use_cases.item3': '必要系統驅動程式：NI MAX（NI VISA 488.2）USB-RS-232 相關驅動',
      'section.use_cases.note': '※ 若系統需支援其他版本作業系統或額外軟體環境，請於需求討論階段主動說明。※ 必要系統驅動程式部分若有搭配其他的韌體或硬體，可能增加額外使用限制',
      'section.use_cases.p1': '本服務主要針對符合下列開發規格的軟硬體系統，             其餘操作環境若有需求，歡迎另行討論可行性。',
      'section.use_cases.subitem1': 'NI MAX（NI VISA 488.2）',
      'section.use_cases.subitem2': 'USB-RS-232 相關驅動',
      'section.use_cases.title': '應用場景',
      'toc.about': '關於橘皮客',
      'toc.client_checklist': '客戶需事先準備的資料',
      'toc.contact': '聯絡資料',
      'toc.gui_style': 'GUI 設計風格示例',
      'toc.pricing': '價目表',
      'toc.process': '專案開發流程',
      'toc.requirements_guide': '客戶需求填寫指引',
      'toc.scope': '服務範圍',
      'toc.terms': '合作條款細節',
      'toc.title': '目錄',
      'toc.use_cases': '應用場景',
    },
    'zh-CN': {
      // TODO: 請依需求逐步翻譯為簡體中文，以下為預設先沿用繁中內容。
      'img.pricing_table.src': 'images/pricing_table.png',
      'img.process_overview.src': 'images/process_overview.png',
      'img.process_stage_1.src': 'images/process_stage_1.png',
      'img.process_stage_2.src': 'images/process_stage_2.png',
      'img.process_stage_3.src': 'images/process_stage_3.png',
      'nav.brand': '橘皮客 GUI 設計服務',
      'nav.home': '回首頁',
      'page.brand': '橘皮客自動化　Gary Chu',
      'page.footer': '本頁內容僅供專案合作與需求溝通使用。若有未盡事宜，歡迎直接與開發方聯繫討論。',
      'page.subtitle': '在自動化與資料導向的時代，我們協助您打造穩定、可靠、具彈性的專業 GUI 介面。',
      'page.title': 'GUI 設計服務流程條款',
      'section.about.list1': '韌性（Resilience）：面對專案中不可避免的挑戰與突發狀況，我們具備足夠的耐力與解決問題的能力，確保系統最終能穩定落地。',
      'section.about.list2': '毅力（Perseverance）：我們不斷優化模組化架構與開發流程，憑藉日積月累的經驗與持續投入，為客戶帶來可靠且高品質的成果。',
      'section.about.list3': '彈性（Flexibility）：每個客戶的需求都不同，我們擅長在既有框架上快速調整，提供最適合的方案，無論是 GUI 設計、硬體控制還是系統整合。',
      'section.about.list4': '我們能夠提供的服務範圍',
      'section.about.list5': '專案的開發流程與時間規劃',
      'section.about.list6': '雙方應遵守的合作條款',
      'section.about.list7': '各項服務的價值與成本依據',
      'section.about.p1': '在當今自動化與數據導向的時代，人機介面（GUI）已不僅僅是顯示數據的工具，             而是客戶與系統互動的核心。',
      'section.about.p2': '我們深信，一個好的設計服務不只是完成專案，而是要陪伴客戶一起走過挑戰，             確保每一步都能帶來價值。',
      'section.about.p3': '因此，我們的服務理念建立在三個核心精神上：',
      'section.about.p4': '本文件的目的，是希望客戶在專案開始之前，就能清楚了解：',
      'section.about.p5': '透過這樣的規劃，我們不僅交付一個 GUI，而是交付一個能伴隨企業成長、             具備韌性、毅力與彈性的完整解決方案，讓客戶能安心專注於核心業務。',
      'section.about.title': '關於橘皮客',
      'section.client_checklist.item1': '現有系統或 Demo 影片（若有）：可以是手機拍攝的操作影片，方便我們了解實際流程。',
      'section.client_checklist.item2': '儀器與硬體清單：包含儀器型號、通訊介面（UART / I2C / SPI / GPIB / LAN / USB）等。',
      'section.client_checklist.item3': '通訊協議與指令文件：例如 SCPI 指令表、通訊時序圖、廠商提供的 PDF 等。',
      'section.client_checklist.item4': '測試流程或 SOP 文件：說明平時如何操作、量測哪些數據、判斷 Pass / Fail 的條件。',
      'section.client_checklist.item5': '報表範例或欄位需求：可提供舊報表或 Excel 範本，標註必需欄位與格式要求。',
      'section.client_checklist.item6': 'GUI 草圖或舊 GUI 截圖（若有）：有助於我們理解排版習慣與風格偏好。',
      'section.client_checklist.item7': '預計使用環境與電腦規格：例如 OS 版本、螢幕解析度、是否在產線環境等。',
      'section.client_checklist.item8': '專案時程與內部里程碑：若您已有內部專案排程，可一併提供，方便我們對齊時程。',
      'section.client_checklist.note': '若以上資料尚未齊備，也歡迎先與我們討論，我們可以協助一起整理，逐步補齊。專案的規格剛開始很難完全確定，但希望透過這份文件以及後續的郵件、開會討論可以協助您逐步達成您喜要的目標!',
      'section.client_checklist.p1': '為了縮短前期溝通時間並提升專案準確度，建議您在首次會議或需求提出前，             儘可能準備以下資料（可先準備已有的部分，其餘可於後續補充）：',
      'section.client_checklist.title': '客戶需事先準備的資料',
      'section.contact.client_eng_item1': '技術討論工程師（負責專案進行中的技術細節討論）稱呼：__________________Mail：__________________手機或 Line ID：__________________',
      'section.contact.client_eng_mail': 'Mail：__________________',
      'section.contact.client_eng_name': '稱呼：__________________',
      'section.contact.client_eng_phone': '手機或 Line ID：__________________',
      'section.contact.client_pm_item1': '專案經理（負責時程、功能與一般溝通）稱呼：__________________Mail：__________________手機或 Line ID：__________________',
      'section.contact.client_pm_mail': 'Mail：__________________',
      'section.contact.client_pm_name': '稱呼：__________________',
      'section.contact.client_pm_phone': '手機或 Line ID：__________________',
      'section.contact.client_pm_title': '客戶端聯絡窗口',
      'section.contact.dev_engineer': '技術工程師：Gary Chu',
      'section.contact.dev_line': 'Line ID：tigarychu',
      'section.contact.dev_mail': 'Mail：gary49902210@gmail.com',
      'section.contact.dev_title': '開發方聯絡窗口（橘皮客自動化）',
      'section.contact.p1': '為了讓專案能順利進行，請客戶提供以下兩位聯絡人資訊：',
      'section.contact.title': '聯絡資料',
      'section.gui_style.item1': '技術型 / 工具型：偏向工程師使用，畫面以表格、參數與 Log 為主，重視資訊密度與操作效率。',
      'section.gui_style.item2': '儀表板型：使用大型數值、指針表、狀態燈號等呈現重點資訊，適合監控與展示。',
      'section.gui_style.item3': '簡潔扁平風格：按鈕與元件設計較為現代、線條簡單，適合對外展示或客戶端使用。',
      'section.gui_style.item4': '客製混合風格：若您有既有軟體或品牌識別（Logo、色系），我們可以依現有風格調整 GUI 視覺。',
      'section.gui_style.note': '若目前尚無特別偏好，也可以先以「清楚、好操作」為主，我們會依常見工程用 GUI 的習慣進行設計。',
      'section.gui_style.p1': '雖然本服務主要以技術功能與穩定性為優先，但介面風格仍會影響使用體驗。             您可以先思考希望整體感覺偏向哪一類型，我們會在設計時盡量配合：',
      'section.gui_style.title': 'GUI 設計風格示例',
      'section.pricing.img_caption': '圖示：GUI 設計服務價目表（請依實際圖片路徑替換 src）',
      'section.pricing.note': '※ 若有大型專案、長期合作或需多階段擴充之情況，歡迎洽談專案制報價。',
      'section.pricing.p1': '各功能項目請參考下方價目表示意圖。實際費用可能會依照             專案複雜度、客製程度及整體規劃而有所調整。',
      'section.pricing.p2': '每一個專案方案，預設皆包含專案完成後 3 個月內，每月 3 小時的客戶服務（線上討論／技術諮詢）。',
      'section.pricing.title': '價目表',
      'section.process.detail_flow_p1': '更細部的階段性流程，將依下列示意圖說明。若您已有內部標準開發流程，             也可以在雙方討論後進行整合。',
      'section.process.detail_flow_title': '階段性細節流程',
      'section.process.img_main_caption': '圖示：專案主要開發流程（請依實際圖片路徑替換 src）',
      'section.process.img_stage1_caption': '圖示：專案階段性流程（第一部分）',
      'section.process.img_stage2_caption': '圖示：專案階段性流程（第二部分）',
      'section.process.img_stage3_caption': '圖示：專案階段性流程（第三部分）',
      'section.process.p1': '企劃進行時，開發方與客戶需要共同配合，並留意以下主要流程。',
      'section.process.rough_timeline_note': '實際時程會依專案範圍、技術難度及資源配合情況調整，將於專案計畫書中明確載明。',
      'section.process.title': '專案開發流程',
      'section.req_guide.end_note': '以上內容不需要一次完成，只要先提供大致方向即可。             我們會在需求訪談與會議中協助補充細節，並整理為正式的專案計畫書。',
      'section.req_guide.flow_item1': '開啟程式 → 選擇 COM Port → 按下「連線」',
      'section.req_guide.flow_item2': '載入測試條件檔 → 按下「開始測試」',
      'section.req_guide.flow_item3': '等測試完成 → 顯示結果 → 匯出報表到指定資料夾',
      'section.req_guide.flow_note': '若有多種情境（例如：工程模式 / 操作員模式），也可以分別描述，我們會協助拆分為不同頁面或權限。',
      'section.req_guide.flow_p1': '請以「使用者實際操作」的角度，簡單描述一個完整流程。例如：',
      'section.req_guide.flow_title': '2. 操作流程（使用步驟）',
      'section.req_guide.gui_layout_item1': '主視窗大致尺寸（例如：1280×720 或全螢幕）',
      'section.req_guide.gui_layout_item2': '按鈕、輸入欄位、列表、圖表等大致位置',
      'section.req_guide.gui_layout_item3': '是否需要多分頁（Tab）或多個對話框視窗',
      'section.req_guide.gui_layout_p1': '您可以使用簡單手繪、PowerPoint、Excel 或任何工具，畫出想像中的畫面配置，             並標註大致位置與功能，例如：「左側為測試設定區、右側為即時曲線圖、下方為 Log 區」。',
      'section.req_guide.gui_layout_title': '1. GUI 版面與畫面配置',
      'section.req_guide.hw_item1': '儀器或搭配硬體型號與廠牌（例如：電源供應器、DMM、示波器、Pico 等）',
      'section.req_guide.hw_item2': '通訊介面：UART / I2C / SPI / GPIB / LAN / USB 等',
      'section.req_guide.hw_item3': '是否有現成範例程式（例如：Python、LabVIEW、C）',
      'section.req_guide.hw_item4': '是否能提供通訊協議、指令表或 SCPI 命令文件',
      'section.req_guide.hw_p1': '若 GUI 需要控制儀器、測試板或其他硬體，請盡量提供以下資訊：',
      'section.req_guide.hw_title': '3. 儀器／硬體控制需求',
      'section.req_guide.intro': '為了讓我們能更精準估算工時與成本，並減少後續反覆修改，             建議您在提出需求時，盡量依照下列項目進行描述。             不需要一次寫得非常完整，可以先用簡單條列，我們會在郵件或會議中協助補充與釐清。',
      'section.req_guide.report_item1': '是否需要 Excel 報表（請提供範例檔或欄位名稱）',
      'section.req_guide.report_item2': '是否需要 CSV / JSON 等機器可讀格式',
      'section.req_guide.report_item3': '是否需支援多次量測結果比對或合併報告',
      'section.req_guide.report_p1': '請簡單說明您希望最後的測試結果以什麼形式呈現，例如：',
      'section.req_guide.report_title': '4. 報表與資料輸出需求',
      'section.req_guide.title': '客戶需求填寫指引',
      'section.req_guide.user_item1': '主要使用者類型：研發 / 量產 / 實驗室 / 教學 等',
      'section.req_guide.user_item2': '是否需要權限區分（例如：一般使用者 vs 管理者）',
      'section.req_guide.user_item3': '預期每天或每週使用頻率',
      'section.req_guide.user_p1': '不同使用者（研發工程師、產線作業員、FAE、客戶端工程師）對介面與功能的需求會不同。             若您能提供預期使用族群與環境，我們可以在設計上更貼近實際需求。',
      'section.req_guide.user_title': '5. 使用者族群與使用情境',
      'section.scope.func1': 'GUI 主視窗設計、選單列（menubar）、對話框',
      'section.scope.func2': '資料顯示（表格、圖表、即時數據）',
      'section.scope.func3': '儀器／硬體控制介面（UART、I2C、SPI、GPIB）',
      'section.scope.func4': '報告輸出（Excel、CSV、自動化格式）',
      'section.scope.func_title': '功能性範圍',
      'section.scope.nonfunc1': '不包含硬體現場調試（如需，將另行報價）',
      'section.scope.nonfunc2': '不包含第三方商業授權軟體費用（例如專業版工具授權等）',
      'section.scope.nonfunc_title': '非功能性範圍（排除事項）',
      'section.scope.title': '服務範圍',
      'section.terms.accept_p1': '當專案完成時，開發方將與客戶於會議中進行測試與驗收。             若專案涉及實體硬體，則需安排實體會議或現場測試。',
      'section.terms.accept_p2': '驗收將依照訂金前雙方確認之專案計畫書與驗收項目進行。             開發方應針對功能缺失進行修正，但不包含 GUI 額外美化調整。             若此階段客戶提出新的需求，將視為新專案或新階段內容，需另行評估與報價。',
      'section.terms.accept_p3': '專案成果交付後，客戶應於一週內支付尾款，以完成結案程序。             結案後，若遇到非原專案計畫中功能缺失之修改需求，將視為新專案需求。',
      'section.terms.accept_title': '六、測試驗收與成果交付',
      'section.terms.change_list1': '小幅調整（通常不另外計價）：文案修正、欄位名稱調整、顏色或字體微調等，不影響整體架構者。',
      'section.terms.change_list2': '中度變更（需評估追加費用）：新增按鈕與對應功能、新增報表格式、增加與新儀器的對接等。',
      'section.terms.change_list3': '重大變更（需重新估價或開新專案）：主要流程改寫、測試邏輯全面調整、作業系統平台改變等。',
      'section.terms.change_note': '通常在初版 GUI 確認後，若版面或流程有大幅變更需求，我們會先與您說明影響範圍與工時，             經雙方同意後再進行調整。',
      'section.terms.change_p1': '為避免專案過程中因需求持續變動而導致時程與成本大幅增加，             雙方將以「專案計畫書」作為主要依據，必要時再透過「變更單」進行調整。',
      'section.terms.change_title': '三、變更需求與加價原則',
      'section.terms.need_eval_list1': '提供 Demo 機與示範操作，並向開發方說明實際需求。',
      'section.terms.need_eval_list2': '由開發方進行 Log 抓取，評估介面協定與實作可行性。',
      'section.terms.need_eval_list3': '開發方與客戶技術工程師進行技術討論，確認需求細節與可行性。',
      'section.terms.need_eval_p1': '開發方將依照客戶提供的相關資料，分析技術可行性、估算開發工時與成本，             並提出所需之測試儀器與相關資源，請客戶評估是否能提供開發所需條件。             若無法提供，雙方將另行討論替代方案與調整方式。',
      'section.terms.need_eval_p2': '對於已有範例程式或明確客製目標的專案，客戶需在韌體或驅動開發前，             提供完整可測試之硬體與接線資訊，以確保能開發出功能相同或可正常對接之系統。             主要需配合事項如下：',
      'section.terms.need_eval_p3': '根據專案複雜程度，如有必要，可行性評估階段可能需收取評估費，將於事前與客戶說明。',
      'section.terms.need_eval_title': '一、需求討論與可行性評估',
      'section.terms.plan_update_p1': '開發方應於收取訂金前提供專案計畫書，             內容包括：對專案需求功能的理解、預計驗收項目與驗收方式。             此文件將作為專案完成時之驗收依據，雙方皆不得單方面修改專案目標與驗收項目。',
      'section.terms.plan_update_p2': '專案啟動後，每2～3 週開發方將向客戶進行進度彙報與已完成功能之展示，             以線上會議為主，並將相關資料上傳至雲端硬碟供客戶參考。             客戶須於會議中協助確認功能是否符合需求，以避免方向偏差造成交期延誤。',
      'section.terms.plan_update_p3': 'GUI（使用者介面）設計將於開發過程中提供初稿給客戶審閱與確認。             完成確認後，除專案計畫書原列之功能必要調整外，將不再進行額外美化或大幅版面修改。',
      'section.terms.plan_update_p4': '客戶應盡量於前期明確提供 GUI 版面初始設計與後續調整需求，             以降低來回修正次數。專案提供3 次免費版面修改，             超過 3 次者，將以每次新台幣 2,000 元計入尾款。             若為開發方遺漏之需求，則不計入此修改次數。',
      'section.terms.plan_update_p5': '開發方與客戶皆需指定一位專案經理與技術溝通窗口（可為同一人），             遇到非預期專案調整或技術討論需求時，得以迅速聯繫並維持專案順利進行。',
      'section.terms.plan_update_title': '五、開發規劃與進度更新',
      'section.terms.quote_deposit_p1': '確認需求並完成可行性評估後，開發方將依結果進行專案時程規劃與報價。             雙方確認專案目標、報價與時程無誤並達成共識後，             客戶需支付20% 訂金，以確認專案計畫書內所載之目標與範圍。',
      'section.terms.quote_deposit_p2': '專案啟動後開始計算時程。若後續有新增或重大修改需求，             需針對新增項目另行估價。若遇開發方無法完成之情況，             將與客戶討論調整計畫與報價方式。',
      'section.terms.quote_deposit_p3': '若客戶需開發方提供原始碼，將依專案大小與難度另行評估費用，             並提供具詳細註解之程式碼。',
      'section.terms.quote_deposit_p4': '訂金收據將以開發方銀行帳戶記錄截圖方式回傳給客戶留存。',
      'section.terms.quote_deposit_title': '二、報價與訂金',
      'section.terms.terminate_list1': '若因開發方遇不可預期因素（例如評估錯誤等）需中止專案，                 客戶可選擇要求全額退還訂金，或接收已完成之部分成果並由雙方協議處理方式。',
      'section.terms.terminate_list2': '若因客戶遇不可預期因素需中止專案，開發方得依照已執行之工作項目與進度進行收費。',
      'section.terms.terminate_title': '四、中止條款與責任歸屬',
      'section.terms.title': '合作條款細節',
      'section.terms.warranty_p1': '專案成果交付後，開發方將提供2 個月功能保固，             期間若發現專案功能缺失，可免費協助修正。',
      'section.terms.warranty_p2': '此外，專案結案後6 個月內，             每月提供最多3 小時的線上討論與售後技術諮詢服務。             若超過此時數，或需開發方到場（on-site）支援，將另行評估費用。',
      'section.terms.warranty_title': '七、後續維護、服務與保固',
      'section.use_cases.item1': '電腦作業系統：Windows 11 24H2',
      'section.use_cases.item2': '報告輸入／輸出工具：Excel 2019 64-bit',
      'section.use_cases.item3': '必要系統驅動程式：NI MAX（NI VISA 488.2）USB-RS-232 相關驅動',
      'section.use_cases.note': '※ 若系統需支援其他版本作業系統或額外軟體環境，請於需求討論階段主動說明。※ 必要系統驅動程式部分若有搭配其他的韌體或硬體，可能增加額外使用限制',
      'section.use_cases.p1': '本服務主要針對符合下列開發規格的軟硬體系統，             其餘操作環境若有需求，歡迎另行討論可行性。',
      'section.use_cases.subitem1': 'NI MAX（NI VISA 488.2）',
      'section.use_cases.subitem2': 'USB-RS-232 相關驅動',
      'section.use_cases.title': '應用場景',
      'toc.about': '關於橘皮客',
      'toc.client_checklist': '客戶需事先準備的資料',
      'toc.contact': '聯絡資料',
      'toc.gui_style': 'GUI 設計風格示例',
      'toc.pricing': '價目表',
      'toc.process': '專案開發流程',
      'toc.requirements_guide': '客戶需求填寫指引',
      'toc.scope': '服務範圍',
      'toc.terms': '合作條款細節',
      'toc.title': '目錄',
      'toc.use_cases': '應用場景',
    }
  };

  const DEFAULT_LANG = 'zh-TW';  // 預設語系

  function getCurrentLanguage() {
    try {
      const saved = localStorage.getItem('lang');
      if (saved && GUI_TRANSLATIONS[saved]) return saved;

      const nav = (navigator.language || navigator.userLanguage || '').trim();
      if (GUI_TRANSLATIONS[nav]) return nav;
      if (nav.startsWith('zh')) return 'zh-TW';
      return DEFAULT_LANG;
    } catch (e) {
      console.error('getCurrentLanguage error:', e);
      return DEFAULT_LANG;
    }
  }

  function applyTranslations(root) {
    try {
      const lang = getCurrentLanguage();
      const dict = GUI_TRANSLATIONS[lang] || {}
      const fallback = GUI_TRANSLATIONS[DEFAULT_LANG] || {};

      const nodes = (root || document).querySelectorAll('[data-i18n]');
      nodes.forEach(el => {
        try {
          const key = el.getAttribute('data-i18n');
          const attr = el.getAttribute('data-i18n-attr');

          let val = undefined;
          if (Object.prototype.hasOwnProperty.call(dict, key)) {
            val = dict[key];
          } else if (Object.prototype.hasOwnProperty.call(fallback, key)) {
            val = fallback[key];
          }

          if (val == null) return;

          if (attr) {
            el.setAttribute(attr, val);
          } else {
            el.innerHTML = val;
          }
        } catch (inner) {
          console.error('applyTranslations node error:', inner);
        }
      });

      document.documentElement.setAttribute('lang', lang);

    } catch (e) {
      console.error('applyTranslations error:', e);
    }
  }

  function setLanguage(lang) {
    try {
      if (!GUI_TRANSLATIONS[lang]) lang = DEFAULT_LANG;
      localStorage.setItem('lang', lang);
      applyTranslations(document);

      const sel = document.getElementById('langSelect');
      if (sel) sel.value = lang;
    } catch (e) {
      console.error('setLanguage error:', e);
    }
  }

  document.addEventListener('DOMContentLoaded', function() {
    try {
      const lang = getCurrentLanguage();
      const sel = document.getElementById('langSelect');
      if (sel) {
        sel.value = lang;
        sel.addEventListener('change', function(ev) {
          setLanguage(ev.target.value);
        });
      }
      applyTranslations(document);
    } catch (e) {
      console.error('ts_cs init error:', e);
    }
  });

  // 將函數掛到全域，方便日後除錯或手動切換語系
  window.guiI18n = {
    getCurrentLanguage,
    setLanguage,
    applyTranslations,
    GUI_TRANSLATIONS
  };
})();
